import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Header />
                {children}
                <footer className="bg-gray-900 text-white py-8 px-4">
                    <div className="max-w-6xl mx-auto text-center">
                        <p className="text-sm text-gray-400">
                            © 2025 鄭雲修. All rights reserved.
                        </p>
                    </div>
                </footer>
            </body>
        </html>
    );
}
